### ISSUE TITLE
Support non-failing "last term" for boolean flags

### ISSUE THREAD

**Issue by infinity0** [dbuenzli/cmdliner#46] opened 2016-02-15 21:46 UTC
I'd like my boolean flags to be robust so that clients of my program can override earlier flags simply by adding `--flag=no`. (Many other programs allow `--no-flag`, but the `--flag=no` seems easier to add to cmdliner.) Currently, `Arg.last` _requires_ at least one flag, so I can't just do `last & flag_all`. Instead, I can try to emulate the behaviour with this:

```
let last_flag_all inf =
  let [..] in
  let env_bool_parse s = [..] in
  Arg.(last @@ opt_all ~vopt:true (env_bool_parse, snd bool) [false] inf)
```

where `[..]` is quite a lot of private code copied from `cmdliner.ml` to make the definitions work.

It works functionally how you'd expect, however the man page ends up not looking right, like this:

```
       --flag[=VAL] (default=true)
```

Ideally it should say something like:

```
       --flag[=true,yes,1|=false,no,0] (absent=false)
```

It would be nice if `cmdliner` supported this in a more easy way, either (1) directly or (2) exposing more of its internals so I can implement it more easily without copying so much code and also be able to have more sensible man page output.

**Comment by infinity0** [comment] 2016-02-15 21:50
Oh, in `let opt_all` it has `absent = Val (lazy "")`; that empty string should probably be `(str_of_pp print v)` instead to be consistent with `let opt`.

**Comment by dbuenzli** [comment] 2016-02-16 09:09
> It would be nice if cmdliner supported this in a more easy way, either (1) directly or (2) exposing more of its internals so I can implement it more easily without copying so much code and also be able to have more sensible man page output.

I don't see what 1) or 2) are here. Neither what's wrong with: 
```
Arg.(last @@ opt_all ~vopt:true bool [false] & info ...) 
```

**Comment by infinity0** [comment] 2016-02-16 14:07
Ah, I overlooked that for some reason. But that still suffers from the confusing help text that I mentioned - `default=true` might be misinterpreted by a quick reader to mean "no flag means true".

To fix this, I think you just need to do [this](#issuecomment-184409555) which I'm guessing will add `(absent=false)` to the help text, which clears things up.

**Comment by dbuenzli** [comment] 2016-02-17 08:36
> To fix this, I think you just need to do this which I'm guessing will add (absent=false) to the help text, which clears things up.

The problem is that `v` is a list and that in general it's unclear the semantics the client wants to give to the list. 

I think you may want to review you initial assumption: 

> Many other programs allow --no-flag, but the --flag=no seems easier to add to cmdliner.)

It's good to behave the way the other programs do and and I don't see what's hard about having a `--no-flag` in cmdliner (see `vflag`).

**Comment by infinity0** [comment] 2016-02-17 13:20
How is it more or less unclear than a non-list value? It is true the client can post-process that value however it likes, but that can happen equally with the existing `absent=XXX` output for non-list values. What's wrong with `pp_print_list`?

`vflag_all` also does not give great help text here. I would end up with two separate options, but ideally it would say `--flag, --no-flag (default:true/false)`.

**Comment by dbuenzli** [comment] 2016-02-17 14:02
> How is it more or less unclear than a non-list value?

It can be for repeatability or `last` or something else. For non-list values it is is easy to play with the converter's formatter to get the right output. 

> ideally it would say --flag, --no-flag (default:true/false)

FWIW I wouldn't understand what that `default` marking does here. I think the options should simply be on their line and an explanation in the doc string.

**Comment by infinity0** [comment] 2016-02-17 14:41
> It can be for repeatability or `last` or something else. For non-list values it is is easy to play with the converter's formatter to get the right output.

For non-list values I can do arbitrary things to it in the same form of how `last` works, as well. That is a separate and independent issue from the fact that `opt_val` and `opt` are inconsistent, which is what we are talking about here.

To properly fix the former, you would (a) let the client override the `absent` field or (b) have `last` et.al. transform `absent` in the appropriate way, instead of using it as justification to keep "absent" out of `opt_val`'s output i.e. hold unrelated features back from being inconsistent / counterintuitive.

> FWIW I wouldn't understand what that `default` marking does here. I think the options should simply be on their line and an explanation in the doc string.

Perhaps say "absent" instead of "default". It's less cluttered to have help text for the same concept in the same block. If a program has multiple boolean flags and I do what you're saying, the reader would quickly become visually overloaded and have to spend (i.e. waste) more of their time to distinguish other *actually distinct* options.

**Comment by dbuenzli** [comment] 2016-02-17 15:11
> the fact that opt_val and opt are inconsistent

`opt_val`, doesn't exist you may be referring to `opt_all`.  If that's the case they are not inconsistent, they render differently, the docs says nothing about how documentation is rendered in general. 

I will maybe review how I generate the documentation for `_all` variants at some point, maybe. In general there is so much you can do automatically without becoming annoying or wrong, so sometimes it's better to do less and let the client clarify in the doc string.

> It's less cluttered to have help text for the same concept in the same block.

Then simply use a *non-repeatable* `opt` with a *non-optional* `bool` argument. This will render the documentation like you want, will make command lines in scripts easier to read and maintain, warn the user when he his using an inconsistent set of options, and avoid the nasty ambiguities you get when using options with optional arguments together with positional arguments (in general I'd advise against using the formers).

**Comment by dbuenzli** [comment] 2017-01-28 19:01
Still unconvinced this is useful and desirable. So I'm closing.

**Closed by dbuenzli** 2017-01-28 19:01 UTC
