### ISSUE TITLE
Warning 44 on using & operator inside open Arg

### ISSUE THREAD

**Issue by hoichi** [dbuenzli/cmdliner#105] opened 2019-02-23 06:39 UTC
Not sure why it hasn’t been reported before, but when you open `Arg` and use the `&` operator, as shown, for example, here, you get warnings like this:

```
File "/home/hoichi/dev/bsdoc/src/Cli.ml", line 27, characters 8-68:
Warning 44: this open statement shadows the value identifier & (which is later used)
File "/home/hoichi/dev/bsdoc/src/Cli.ml", line 35, characters 8-136:
Warning 44: this open statement shadows the value identifier & (which is later used)
File "/home/hoichi/dev/bsdoc/src/Cli.ml", line 60, characters 8-140:
...
```
At first I was thinking this is the BuckleScript problem, (the project is in ReasonML), but it is reproducible in `utop`: you shadow `&`, you get the warning.

I know `&` has different precedence than `@@`, but was it (and the fact that it looks better) important enough to introduce a non-standard operator and shadow the pervasive one? More importantly, can one somehow not get the warning (other than disabling warning 44 completely)?

**Comment by dbuenzli** [comment] 2019-02-25 09:30
> Not sure why it hasn’t been reported before,

Maybe because I don't and never saw this, could you please provide a full repro case.

> I know `&` has different precedence than `@@`, but was it (and the fact that it looks better) important enough to introduce a non-standard operator and shadow the pervasive one?

Always consider history and context when you judge design choices; `@@` didn't exist when `Cmdliner` was created, besides `&` in the stdlib was deprecated, so it felt a good character to use.

> More importantly, can one somehow not get the warning (other than disabling warning 44 completely)?

I never tweak any of the warnings provided by the stock OCaml compiler so I'm not sure how you are getting that one. Here's what I get: 

```
> ocamlc -version
4.07.1
> cat test.ml
open Cmdliner.Arg (* Note, don't do this rather use Arg.() *)
let f x y = x & y
> ocamlfind ocamlopt -linkpkg -package cmdliner test.ml
> 
```

**Comment by dbuenzli** [comment] 2019-03-04 09:15
Closing this since I can't reproduce. Feel free to continue the discussion if you have more details.

**Closed by dbuenzli** 2019-03-04 09:15 UTC

**Comment by anne-pacalet** [comment] 2019-12-06 15:44
It appears if you activate all the warnings:
```
$ ocamlc -version
4.08.1
$ cat cmd.ml 
open Cmdliner
let _ = Arg.(value & opt string "" & info ["o"]  ~doc:"txt" ~docv:"X")
$ ocamlfind ocamlopt -w @a -package cmdliner -linkpkg cmd.ml 
File "cmd.ml", line 1, characters 0-13:
1 | open Cmdliner
    ^^^^^^^^^^^^^
Error (warning 44): this open statement shadows the module identifier Arg (which is later used)
File "cmd.ml", line 2, characters 8-11:
2 | let _ = Arg.(value & opt string "" & info ["o"]  ~doc:"txt" ~docv:"X")
            ^^^
Error (warning 44): this open statement shadows the value identifier & (which is later used)
```

**Comment by ddemange** [comment] 2020-04-01 06:19
A possible workaround is to use a `let open! Arg in`, when the shadowing of `&` is "intentional" (see https://caml.inria.fr/pub/docs/manual-ocaml/overridingopen.html). 
This way, the warning is disabled as locally as can be. This has been suggested to me, and I thought it would be useful to document it here.
