### ISSUE TITLE
Cmdliner's paging does not work on my machine

### ISSUE THREAD

**Issue by hbr** [dbuenzli/cmdliner#139] opened 2022-03-09 10:48 UTC
It seems that cmdliner displays help text via a pager by default. Is there a possibility to make 'plain' the default?

Reason: On my machine the pager does not work correctly. I would prefer to force in the source code, that no pager is used.

**Comment by dbuenzli** [comment] 2022-03-09 11:06
No, I'm afraid. Duplicate of https://github.com/dbuenzli/cmdliner/issues/102

If on your machine the pager does not work correctly, define `PAGER=cat` in your environment that should solve your problem for even more programs.

**Comment by hbr** [comment] 2022-03-09 13:14
Thanks for the comment and the reference to the discussion. I understand your point. But maybe there is something wrong on my side or there is a bug. Your suggested solution with `PAGER=cat` does not work.

If I run my program with `prog --help=plain | less` or `prog --help=plain | cat` everything is fine. However with `PAGER=cat` or `PAGER=less` the command `prog --help` puts the output in an undefined state. It seems to be in a pager, because I can end it by typing `q`. But there is not any help text.

My program is as simple as your chorus example. Is there a possibility to find out whats wrong?

**Comment by dbuenzli** [comment] 2022-03-09 15:39
Ah you should have said `cmdliner`'s paging does not work on my machine, not the pager does not work on my machine ! 

Of course we should find what's wrong. 

1. What's your operating system ? 
2. What's the output of `env` ? (remove anything that may be private)
3. The whole paging logic is contained [here](https://github.com/dbuenzli/cmdliner/blob/74daf226fbacdd29862a01c85fe37c6595b374bf/src/cmdliner_manpage.ml#L438-L481), maybe you can get a feel of what goes wrong on your machine.

**Comment by hbr** [comment] 2022-03-09 15:47
Thanks for trying to help.

1. I am working on "macOS Catalina 10.15.7"
2. Output of "env"

```
CAML_LD_LIBRARY_PATH=/Users/helmut/.opam/default/lib/stublibs:/Users/helmut/.opam/default/lib/ocaml/stublibs:/Users/helmut/.opam/default/lib/ocaml
LDFLAGS=-L/usr/local/opt/openssl@1.1/lib
TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
CPPFLAGS=-I/usr/local/opt/openssl@1.1/include
TMPDIR=/var/folders/3d/dgwp3j250wg8q9dpjy2v038h0000gn/T/
TERM_PROGRAM_VERSION=433
OLDPWD=/Users/helmut
OPAM_SWITCH_PREFIX=/Users/helmut/.opam/default
TERM_SESSION_ID=A35575E4-9735-4ACC-96FA-EA4DB0B310D0
OCAML_TOPLEVEL_PATH=/Users/helmut/.opam/default/lib/toplevel
USER=helmut
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.QT2dbldZ0T/Listeners
PATH=/Users/helmut/.opam/default/bin:/usr/local/opt/sphinx-doc/bin:/usr/local/opt/openssl@1.1/bin:/Users/helmut/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
LaunchInstanceID=E1DDCB67-044D-4AB4-A529-602783AC7DAA
PWD=/Users/helmut/myprogs/alba/program
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/helmut
SHLVL=1
LOGNAME=helmut
LC_CTYPE=UTF-8
PKG_CONFIG_PATH=/Users/helmut/.opam/default/lib/pkgconfig:
DISPLAY=/private/tmp/com.apple.launchd.TJ0l6hEgMu/org.macosforge.xquartz:0
OPAMNOENVNOTICE=true
SECURITYSESSIONID=186a7
_=/usr/bin/env

```

**Comment by dbuenzli** [comment] 2022-03-09 15:56
Does either of these work ?

```
prog --help=groff | mandoc -m man -K utf-8 -T utf8
prog --help=groff | mandoc -m man -K utf-8 -T utf8 | less -R
```

**Comment by hbr** [comment] 2022-03-09 16:02
Both work perfectly.

**Comment by hbr** [comment] 2022-03-09 16:05
Does cmdliner need `mandoc`? I did not have `mandoc` on my machine. But now I have installed it via `brew install mandoc` and now the program does work perfectly. I cannot reproduce the problem anymore. Should I uninstall `mandoc`?

**Comment by dbuenzli** [comment] 2022-03-09 16:22
> Does cmdliner need `mandoc`?

Not necessarily. It will try [a few things](https://github.com/dbuenzli/cmdliner/blob/74daf226fbacdd29862a01c85fe37c6595b374bf/src/cmdliner_manpage.ml#L459-L462). 

But since you hadn't `mandoc` in your `PATH`, it went with `groff` and on macos the invocation it tries is not supported because it's too old (see 3fe9fcf5ea991bb3bf37117fd4c7 for details). This convoluted logic is what we tried @MisterDA tried to eventually get UTF-8 manpages). 

I'm very surprised stock macos 11 (my machine) has `/usr/bin/mandoc` but `10` doesn't have it. Is there any reference of which indicates which tools are by default per macos version ?

**Comment by hbr** [comment] 2022-03-10 08:50
Just a curios question? Isn't it possible to check the availability of programs before using them? On a unix machine (Mac or Linux) I would issue `Sys.command "which -s mandoc"` and the return value should give the required information. But I don't know, if there is a portable way that works on windows machines as well.

**Comment by dbuenzli** [comment] 2022-03-11 22:55
> Isn't it possible to check the availability of programs before using them?

Of course it is, cmdliner does exactly, that and does the correct thing on windows. The problem is that macos ships with an uterly outdated `groff`.

**Comment by dbuenzli** [comment] 2022-03-14 12:56
@hbr closing this in favour of https://github.com/dbuenzli/cmdliner/issues/140 which is the same issue.

**Closed by dbuenzli** 2022-03-14 12:56 UTC
