### ISSUE TITLE
Better error message about missing arguments for subcommands

### ISSUE THREAD

**Issue by freehck** [dbuenzli/cmdliner#39] opened 2015-12-03 13:19 UTC
```
% bf2 buildpkg       
bf2: required argument PLATFORM is missing
Usage: bf2 buildpkg [OPTION]... PKGNAME VERSION PLATFORM
```

Obviously it should be reported about the missing argument PKGNAME.

I suppose the problem is in intertal command matching. Cmdliner sees that the 3rd parameter of command is missed. And reported that there's not the 3rd parameter of **sub**command in the error message.

The code to reproduce it:

``` ocaml
let buildpkg_cmd =
  let doc = "..." in
  let man = help_secs in

  let pkgname =
    Arg.(required & pos 0 (some string) None & info [] ~docv:"PKGNAME") in
  let version =
    Arg.(required & pos 1 (some string) None & info [] ~docv:"VERSION") in
  let platform =
    Arg.(required & pos 2 (some string) None & info [] ~docv:"PLATFORM") in

  Term.(...),
  Term.info "buildpkg" ~doc ~man
```

and eventually:

``` ocaml
let () = match Term.eval_choice default_cmd [buildpkg_cmd] with
  | `Error _ -> exit 1
  | _ -> exit 0
```

**Comment by dbuenzli** [comment] 2015-12-03 13:44
> Obviously it should be reported about the missing argument PKGNAME.

Well obviously the `PLATFORM` parameter is also missing so this is not a wrong error message... but yes maybe I could start to report from the left. Which error is reported if you respectively specify one, and two positional arguments ?

**Comment by dbuenzli** [comment] 2015-12-03 13:44
Also a fully reproducible test case would be nice.

**Comment by dbuenzli** [comment] 2015-12-03 13:50
I think from a user point of view we should simply report all missing required arguments, not stop at the first one.

**Comment by hcarty** [comment] 2015-12-03 16:27
Agreed, I'd prefer a report of all missing required arguments if that's reasonable.

If only one is reported then the first missing would be nice to have.

**Comment by freehck** [comment] 2015-12-04 21:34
I'll supply you with reproducible examples after holidays, okay? I'm a little bit busy now.
Well, I'd prefer an error message either with only first missed parameter because I can easily determine the set of missed parameters from the 2nd line with "Usage" string.

**Comment by dbuenzli** [comment] 2015-12-05 11:21
> Well, I'd prefer an error message either with only first missed parameter because I can easily determine the set of missed parameters from the 2nd line with "Usage" string.

I'd say that the usage line only allows you to see at which position the missing arguments are due. 

If the error message only tells you "required argument PKGNAME is missing" your brain will likely focus to fill in PKGNAME, failing to realize other required arguments are missing. In other words it's a misleading error message that will likely bring you to a new erroring interaction. 

If the error is "required arguments PKGNAME, VERSION and PLATFORM are missing", you'll be more likely to take care to try to fill in all the arguments and the usage line will help you figure out at which position the arguments are due.

**Comment by dbuenzli** [comment] 2017-02-02 13:00
In fact the problem is even worse: the actual argument that is reported depends on the way you construct your term.

**Comment by dbuenzli** [comment] 2017-02-02 23:45
This should be fixed, all missing required arguments should be reported, in order. Thanks for the report.

**Comment by dbuenzli** [comment] 2017-02-03 00:16
This introduced the regression that we can no longer as for `--help` if the tool has required arguments and they are not provided. We should test if help is requested before raising the error.

**Closed** 2017-02-03 14:39 UTC
Labels: enhancement
