### ISSUE TITLE
Catch Not_found in Buffer.add_substitute usages and raise an appropriate Invalid_argument exception

### ISSUE THREAD

**Issue by avsm** [dbuenzli/cmdliner#20] opened 2015-01-08 22:06 UTC
If I use ocamlscript to run a cmdliner-based `--help` that uses `tname` in the manpage, it raises Not_found.  This is probably because ocamlscript doesn't supply a Sys.argv when executing the script, so the argv list is empty. Not had a chance to look further.

```
OCAMLRUNPARAM=b ./generate_html.ml  --help                                                                                               
generate-opam-html: internal error, uncaught exception:
                    Not_found
                    Raised at file "buffer.ml", line 123, characters 27-36
                    Called from file "buffer.ml", line 145, characters 16-62
                    Called from file "buffer.ml", line 164, characters 29-47
                    Called from file "format.ml", line 1169, characters 28-44
                    Called from file "list.ml", line 73, characters 12-15
                    Called from file "format.ml", line 1109, characters 4-20
                    Called from file "format.ml", line 1169, characters 28-44
```

**Comment by avsm** [comment] 2015-01-08 22:08
That diagnosis was completely incorrect.  It looks like this line in the `man` section caused it:

```
$(i,https://github.com/avsm/ocaml-docker/scripts)
```

**Comment by dbuenzli** [comment] 2015-01-10 12:41
Do you have a link to the offending code ? I just tried that format string in the help of `chorus.ml` but it doesn't raise.

**Comment by dbuenzli** [comment] 2015-01-31 00:03
@avsm I'll soon make a release for removing the dependency on ocamlfind. A fix for this could be in if you give me more details.

**Comment by dbuenzli** [comment] 2015-02-06 09:16
Can't reproduce. Feel free to reopen with a repro case.

**Comment by avsm** [comment] 2015-02-06 09:20
Apologies -- been too busy to try and repro.  I'll reopen when I find the offending code and have a smaller test case.

**Comment by dbuenzli** [comment] 2015-02-06 10:02
No problem.

**Comment by dbuenzli** [comment] 2015-02-27 15:11
In fact I think I found the problem while reading `Buffer`'s documentation: you most likely forgot to close a formatting instruction `$(i,text)`, `$(b,text)`, `$(mname)`, etc. at some point.

Cmdliner uses [`Buffer.add_substitute`](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Buffer.html#VALadd_substitute) in [all](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L257) [these](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L259) [places](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L474). If a `$(ID)` variable is opened and not closed – e.g. `$(i,bla` – `add_substitute` raises `Not_found`. 

Of course `Cmdliner` should catch that and raise an `Invalid_argument` exception at the right place indicating presence of a non-well formed documentation string. 

(This shows again that exceptions are evil and hard to track... I hope mirageos will take the right step...)

**Comment by dbuenzli** [comment] 2015-08-30 22:11
[Here's](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L1039) another potential `Not_found` that should be turned into `Invalid_argument`.

**Closed** 2015-09-15 10:05 UTC
